//! Generator of the bwapi crate: `bwapi.api` → `syn` → IR → C API (`bwapi_c.h`),
//! C++ thunks implementing it, and the Rust API over it.

pub mod c;
pub mod cpp;
pub mod ir;
pub mod lower;
pub mod names;
pub mod parse;
pub mod rust;

/// First line of every generated file.
pub const GENERATED_HEADER: &str =
    "// @generated by `cargo xtask generate` from bwapi.api. DO NOT EDIT.";

pub struct OutputFile {
    /// Path relative to the output directory.
    pub path: String,
    pub contents: String,
}

pub struct Output {
    /// `crates/bwapi/cpp/include/bwapi_c.h`.
    pub header: String,
    /// Files of `crates/bwapi/cpp/generated`.
    pub cpp: Vec<OutputFile>,
    /// Files of `crates/bwapi/src/generated`, before `rustfmt`.
    pub rust: Vec<OutputFile>,
}

/// Parses and lowers a manifest.
pub fn lower_str(src: &str) -> syn::Result<ir::Api> {
    let file: parse::File = syn::parse_str(src)?;
    lower::lower(&file)
}

/// Generates all projections. Errors are rendered as `path:line:column: message`.
pub fn generate(path: &str, src: &str) -> Result<Output, String> {
    let api = lower_str(src).map_err(|e| render_errors(path, &e))?;
    Ok(Output {
        header: c::generate(&api),
        cpp: cpp::generate(&api),
        rust: rust::generate(&api),
    })
}

/// Appends `text` to the output file `path`, creating it with `header` first.
fn append(files: &mut Vec<OutputFile>, path: String, header: &str, text: &str) {
    match files.iter_mut().find(|f| f.path == path) {
        Some(f) => f.contents.push_str(text),
        None => files.push(OutputFile {
            path,
            contents: format!("{header}{text}"),
        }),
    }
}

pub fn render_errors(path: &str, errors: &syn::Error) -> String {
    errors
        .clone()
        .into_iter()
        .map(|e| {
            let start = e.span().start();
            format!("{path}:{}:{}: error: {e}", start.line, start.column + 1)
        })
        .collect::<Vec<_>>()
        .join("\n")
}
