// @generated by `cargo xtask generate` from bwapi.api. DO NOT EDIT.
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
#define BWAPI_C_NOEXCEPT noexcept
extern "C" {
#else
#define BWAPI_C_NOEXCEPT
#endif

/* Values. */

typedef struct Position { int32_t x; int32_t y; } Position;
typedef struct TilePosition { int32_t x; int32_t y; } TilePosition;
typedef struct WalkPosition { int32_t x; int32_t y; } WalkPosition;
typedef struct Pair { int32_t first; int32_t second; } Pair;

/* BWAPI::Event: one callback of the module. */
typedef struct Event_ Event;
/* BWAPI::AIModule. */
typedef struct AIModule_ AIModule;

/* Room for an iterator over a set: it is moved by copying the bytes. */
typedef struct SetCursor { uint64_t words[4]; } SetCursor;

/* A string or a vector returned by the library: `len` elements of the type the
   function names. `data` comes from bwapi_c_alloc_slice, or is null when `len`
   is 0; the caller owns it and frees it. */
typedef struct Slice { void* data; size_t len; } Slice;

/* Handles: BWAPI interfaces, used only by pointer. */

typedef struct Unit_ Unit; /* BWAPI::UnitInterface */
typedef struct Player_ Player; /* BWAPI::PlayerInterface */
typedef struct Force_ Force; /* BWAPI::ForceInterface */
typedef struct Bullet_ Bullet; /* BWAPI::BulletInterface */
typedef struct Region_ Region; /* BWAPI::RegionInterface */
typedef struct Game_ Game; /* BWAPI::Game */
typedef struct Unitset_ Unitset; /* const BWAPI::Unitset& */
typedef struct UnitQuery_ UnitQuery; /* BWAPI::Unitset by value */
typedef struct Playerset_ Playerset; /* const BWAPI::Playerset& */
typedef struct PlayerQuery_ PlayerQuery; /* BWAPI::Playerset by value */
typedef struct Forceset_ Forceset; /* const BWAPI::Forceset& */
typedef struct ForceQuery_ ForceQuery; /* BWAPI::Forceset by value */
typedef struct Bulletset_ Bulletset; /* const BWAPI::Bulletset& */
typedef struct BulletQuery_ BulletQuery; /* BWAPI::Bulletset by value */
typedef struct Regionset_ Regionset; /* const BWAPI::Regionset& */
typedef struct RegionQuery_ RegionQuery; /* BWAPI::Regionset by value */

/* Type ids and enums: the integer value of the C++ type. */

typedef int32_t UnitType; /* BWAPI::UnitType */
typedef int32_t TextColor; /* BWAPI::Text::Enum */
typedef int32_t EventType; /* BWAPI::EventType::Enum */

/* Required: the user of this library defines these functions. */

/* Memory for `count` elements of `elemSize` bytes aligned to `elemAlign`: the
   data of a Slice. Called only with `count` > 0; must not return null. */
void* bwapi_c_alloc_slice(size_t count, size_t elemSize, size_t elemAlign) BWAPI_C_NOEXCEPT;

/* Every callback of a module created by bwapi_c_new_module. The event lives for
   the duration of the call. */
void bwapi_c_on_event(void* module, Game* game, const Event* event) BWAPI_C_NOEXCEPT;


/* Module. */

/* For `gameInit` of the bot DLL: sets BWAPI::BroodwarPtr. */
void bwapi_c_game_init(Game* game) BWAPI_C_NOEXCEPT;
/* For `newAIModule` of the bot DLL: a module passing its callbacks to bwapi_c_on_event. */
AIModule* bwapi_c_new_module(void* module) BWAPI_C_NOEXCEPT;

/* Event: which fields are set depends on the type. */

EventType Event_getType(const Event* self) BWAPI_C_NOEXCEPT;
Unit* Event_getUnit(const Event* self) BWAPI_C_NOEXCEPT;
Player* Event_getPlayer(const Event* self) BWAPI_C_NOEXCEPT;
Position Event_getPosition(const Event* self) BWAPI_C_NOEXCEPT;
/* The bytes belong to the event. */
void Event_getText(const Event* self, const char** ptr, size_t* len) BWAPI_C_NOEXCEPT;
bool Event_isWinner(const Event* self) BWAPI_C_NOEXCEPT;

/*
 * Sets. `{Set}` is a live set owned by the game; `{Query}` is a set returned by
 * value, owned by the caller until {Query}_release. Iteration: `atEnd` reports
 * exhaustion, `next` requires `!atEnd`.
 */

size_t Unitset_size(const Unitset* self) BWAPI_C_NOEXCEPT;
bool Unitset_contains(const Unitset* self, Unit* elem) BWAPI_C_NOEXCEPT;
void Unitset_begin(const Unitset* self, SetCursor* cursor) BWAPI_C_NOEXCEPT;
bool UnitsetCursor_atEnd(const SetCursor* self) BWAPI_C_NOEXCEPT;
Unit* UnitsetCursor_next(SetCursor* self) BWAPI_C_NOEXCEPT;
size_t UnitsetCursor_remaining(const SetCursor* self) BWAPI_C_NOEXCEPT;
bool UnitQuery_atEnd(const UnitQuery* self) BWAPI_C_NOEXCEPT;
Unit* UnitQuery_next(UnitQuery* self) BWAPI_C_NOEXCEPT;
size_t UnitQuery_remaining(const UnitQuery* self) BWAPI_C_NOEXCEPT;
void UnitQuery_release(UnitQuery* self) BWAPI_C_NOEXCEPT;

size_t Playerset_size(const Playerset* self) BWAPI_C_NOEXCEPT;
bool Playerset_contains(const Playerset* self, Player* elem) BWAPI_C_NOEXCEPT;
void Playerset_begin(const Playerset* self, SetCursor* cursor) BWAPI_C_NOEXCEPT;
bool PlayersetCursor_atEnd(const SetCursor* self) BWAPI_C_NOEXCEPT;
Player* PlayersetCursor_next(SetCursor* self) BWAPI_C_NOEXCEPT;
size_t PlayersetCursor_remaining(const SetCursor* self) BWAPI_C_NOEXCEPT;
bool PlayerQuery_atEnd(const PlayerQuery* self) BWAPI_C_NOEXCEPT;
Player* PlayerQuery_next(PlayerQuery* self) BWAPI_C_NOEXCEPT;
size_t PlayerQuery_remaining(const PlayerQuery* self) BWAPI_C_NOEXCEPT;
void PlayerQuery_release(PlayerQuery* self) BWAPI_C_NOEXCEPT;

size_t Forceset_size(const Forceset* self) BWAPI_C_NOEXCEPT;
bool Forceset_contains(const Forceset* self, Force* elem) BWAPI_C_NOEXCEPT;
void Forceset_begin(const Forceset* self, SetCursor* cursor) BWAPI_C_NOEXCEPT;
bool ForcesetCursor_atEnd(const SetCursor* self) BWAPI_C_NOEXCEPT;
Force* ForcesetCursor_next(SetCursor* self) BWAPI_C_NOEXCEPT;
size_t ForcesetCursor_remaining(const SetCursor* self) BWAPI_C_NOEXCEPT;
bool ForceQuery_atEnd(const ForceQuery* self) BWAPI_C_NOEXCEPT;
Force* ForceQuery_next(ForceQuery* self) BWAPI_C_NOEXCEPT;
size_t ForceQuery_remaining(const ForceQuery* self) BWAPI_C_NOEXCEPT;
void ForceQuery_release(ForceQuery* self) BWAPI_C_NOEXCEPT;

size_t Bulletset_size(const Bulletset* self) BWAPI_C_NOEXCEPT;
bool Bulletset_contains(const Bulletset* self, Bullet* elem) BWAPI_C_NOEXCEPT;
void Bulletset_begin(const Bulletset* self, SetCursor* cursor) BWAPI_C_NOEXCEPT;
bool BulletsetCursor_atEnd(const SetCursor* self) BWAPI_C_NOEXCEPT;
Bullet* BulletsetCursor_next(SetCursor* self) BWAPI_C_NOEXCEPT;
size_t BulletsetCursor_remaining(const SetCursor* self) BWAPI_C_NOEXCEPT;
bool BulletQuery_atEnd(const BulletQuery* self) BWAPI_C_NOEXCEPT;
Bullet* BulletQuery_next(BulletQuery* self) BWAPI_C_NOEXCEPT;
size_t BulletQuery_remaining(const BulletQuery* self) BWAPI_C_NOEXCEPT;
void BulletQuery_release(BulletQuery* self) BWAPI_C_NOEXCEPT;

size_t Regionset_size(const Regionset* self) BWAPI_C_NOEXCEPT;
bool Regionset_contains(const Regionset* self, Region* elem) BWAPI_C_NOEXCEPT;
void Regionset_begin(const Regionset* self, SetCursor* cursor) BWAPI_C_NOEXCEPT;
bool RegionsetCursor_atEnd(const SetCursor* self) BWAPI_C_NOEXCEPT;
Region* RegionsetCursor_next(SetCursor* self) BWAPI_C_NOEXCEPT;
size_t RegionsetCursor_remaining(const SetCursor* self) BWAPI_C_NOEXCEPT;
bool RegionQuery_atEnd(const RegionQuery* self) BWAPI_C_NOEXCEPT;
Region* RegionQuery_next(RegionQuery* self) BWAPI_C_NOEXCEPT;
size_t RegionQuery_remaining(const RegionQuery* self) BWAPI_C_NOEXCEPT;
void RegionQuery_release(RegionQuery* self) BWAPI_C_NOEXCEPT;

/* BWAPI::UnitInterface */

int32_t Unit_getID(Unit* self) BWAPI_C_NOEXCEPT;
bool Unit_exists(Unit* self) BWAPI_C_NOEXCEPT;
Player* Unit_getPlayer(Unit* self) BWAPI_C_NOEXCEPT;
UnitType Unit_getType(Unit* self) BWAPI_C_NOEXCEPT;
Position Unit_getPosition(Unit* self) BWAPI_C_NOEXCEPT;
bool Unit_isIdle(Unit* self) BWAPI_C_NOEXCEPT;
UnitQuery* Unit_getUnitsInRadius(Unit* self, int32_t radius) BWAPI_C_NOEXCEPT;
bool Unit_attack_d(Unit* self, Unit* target) BWAPI_C_NOEXCEPT;
bool Unit_attack(Unit* self, Unit* target, bool shiftQueueCommand) BWAPI_C_NOEXCEPT;
bool Unit_gather_d(Unit* self, Unit* target) BWAPI_C_NOEXCEPT;
bool Unit_gather(Unit* self, Unit* target, bool shiftQueueCommand) BWAPI_C_NOEXCEPT;

/* BWAPI::PlayerInterface */

int32_t Player_getID(Player* self) BWAPI_C_NOEXCEPT;
void Player_getName(Player* self, Slice* out) BWAPI_C_NOEXCEPT; /* out: uint8_t, a string without a terminating zero */
const Unitset* Player_getUnits(Player* self) BWAPI_C_NOEXCEPT;

/* BWAPI::ForceInterface */

int32_t Force_getID(Force* self) BWAPI_C_NOEXCEPT;
void Force_getName(Force* self, Slice* out) BWAPI_C_NOEXCEPT; /* out: uint8_t, a string without a terminating zero */
PlayerQuery* Force_getPlayers(Force* self) BWAPI_C_NOEXCEPT;

/* BWAPI::BulletInterface */

int32_t Bullet_getID(Bullet* self) BWAPI_C_NOEXCEPT;
bool Bullet_exists(Bullet* self) BWAPI_C_NOEXCEPT;

/* BWAPI::RegionInterface */

int32_t Region_getID(Region* self) BWAPI_C_NOEXCEPT;
UnitQuery* Region_getUnits(Region* self) BWAPI_C_NOEXCEPT;

/* BWAPI::Game */

const Forceset* Game_getForces(Game* self) BWAPI_C_NOEXCEPT;
const Playerset* Game_getPlayers(Game* self) BWAPI_C_NOEXCEPT;
const Unitset* Game_getAllUnits(Game* self) BWAPI_C_NOEXCEPT;
const Unitset* Game_getMinerals(Game* self) BWAPI_C_NOEXCEPT;
const Bulletset* Game_getBullets(Game* self) BWAPI_C_NOEXCEPT;
const Regionset* Game_getAllRegions(Game* self) BWAPI_C_NOEXCEPT;
int32_t Game_getFrameCount(Game* self) BWAPI_C_NOEXCEPT;
void Game_getStartLocations(Game* self, Slice* out) BWAPI_C_NOEXCEPT; /* out: TilePosition */
Player* Game_self(Game* self) BWAPI_C_NOEXCEPT;
void Game_sendText(Game* self, const char* text, size_t textLen) BWAPI_C_NOEXCEPT;
void Game_drawTextScreen(Game* self, Position position, const char* text, size_t textLen) BWAPI_C_NOEXCEPT;

/* BWAPI::UnitType */

void UnitType_getName(UnitType self, Slice* out) BWAPI_C_NOEXCEPT; /* out: uint8_t, a string without a terminating zero */
Pair UnitType_whatBuilds(UnitType self) BWAPI_C_NOEXCEPT;
bool UnitType_isWorker(UnitType self) BWAPI_C_NOEXCEPT;

/* Constants. */

enum {
  UnitTypes_Terran_SCV = 7,
  UnitTypes_Protoss_Probe = 64,
  UnitTypes_Zerg_Drone = 41,
};

enum {
  TextColor_Previous = 1,
  TextColor_Default = 2,
  TextColor_Yellow = 3,
  TextColor_White = 4,
  TextColor_Grey = 5,
  TextColor_Red = 6,
  TextColor_Green = 7,
  TextColor_BrightRed = 8,
  TextColor_Invisible = 11,
  TextColor_Blue = 14,
  TextColor_Teal = 15,
  TextColor_Purple = 16,
  TextColor_Orange = 17,
  TextColor_Align_Right = 18,
  TextColor_Align_Center = 19,
  TextColor_Invisible2 = 20,
  TextColor_Brown = 21,
  TextColor_PlayerWhite = 22,
  TextColor_PlayerYellow = 23,
  TextColor_DarkGreen = 24,
  TextColor_LightYellow = 25,
  TextColor_Cyan = 26,
  TextColor_Tan = 27,
  TextColor_GreyBlue = 28,
  TextColor_GreyGreen = 29,
  TextColor_GreyCyan = 30,
  TextColor_Turquoise = 31,
};

enum {
  EventType_MatchStart = 0,
  EventType_MatchEnd = 1,
  EventType_MatchFrame = 2,
  EventType_MenuFrame = 3,
  EventType_SendText = 4,
  EventType_ReceiveText = 5,
  EventType_PlayerLeft = 6,
  EventType_NukeDetect = 7,
  EventType_UnitDiscover = 8,
  EventType_UnitEvade = 9,
  EventType_UnitShow = 10,
  EventType_UnitHide = 11,
  EventType_UnitCreate = 12,
  EventType_UnitDestroy = 13,
  EventType_UnitMorph = 14,
  EventType_UnitRenegade = 15,
  EventType_SaveGame = 16,
  EventType_UnitComplete = 17,
  EventType_None = 18,
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
