[package]
name = "bwapi"
description = "Rust bindings to the Starcraft Broodwar game API"
keywords = ["starcraft", "broodwar", "api", "binding"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
include = ["/Cargo.toml", "/build.rs", "/cpp/**", "/src/**", "/vendor/bwapi/bwapi/include/BWAPI.h", "/vendor/bwapi/bwapi/include/BWAPI/**"]
links = "bwapi"

[dependencies]

[build-dependencies]
cc = "1.2"
